//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int LivreID { get; set; }
        public string LivreName { get; set; }
        public Nullable<System.DateTime> DateParution { get; set; }
    }
}
