//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataBaseFirstDemoEntities : DbContext
    {
        public DataBaseFirstDemoEntities()
            : base("name=DataBaseFirstDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Livre> Livre { get; set; }
        public virtual DbSet<LivreUtilisateur> LivreUtilisateur { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    
        public virtual ObjectResult<GetAllLivre_Result> GetAllLivre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLivre_Result>("GetAllLivre");
        }
    
        public virtual ObjectResult<GetAllUtilisateurs_Result> GetAllUtilisateurs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUtilisateurs_Result>("GetAllUtilisateurs");
        }
    
        public virtual ObjectResult<GetPostFromId_Result> GetPostFromId(Nullable<int> postId)
        {
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPostFromId_Result>("GetPostFromId", postIdParameter);
        }
    }
}
